name: pipeline

on: [push]

jobs:
  prereqs:
    runs-on: ubuntu-latest
    steps:
      - name: Install libx11-dev
        run: sudo apt-get update && sudo apt-get install -y libx11-dev
  go:
    needs:
      - prereqs
    uses: pete911/github-actions/.github/workflows/go.yml@main
  go-release:
    needs:
      - go
    permissions:
      contents: write
    uses: pete911/github-actions/.github/workflows/go-releaser.yml@main
    secrets:
      PUBLIC_REPO_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
